# Generated by Django 3.0.5 on 2020-10-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phoneNumber',
            field=models.IntegerField(default='0', unique=True),
        ),
    ]
