# Generated by Django 3.0.5 on 2020-10-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0002_auto_20201008_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartement',
            old_name='number',
            new_name='balcony',
        ),
        migrations.AddField(
            model_name='appartement',
            name='bathroom',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appartement',
            name='init_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appartement',
            name='loggia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appartement',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
