# Generated by Django 3.0.5 on 2020-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0003_auto_20201010_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='plan',
            field=models.ImageField(default='plans/f2.jpeg', upload_to='plans'),
        ),
    ]
