# Generated by Django 3.0.5 on 2020-10-10 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0004_appartement_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='init_price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.CreateModel(
            name='BuyingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=50)),
                ('birthday', models.DateField()),
                ('birthplace', models.CharField(default='', max_length=255)),
                ('adress', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('identity', models.ImageField(default='', upload_to='identities')),
                ('furniture', models.CharField(default='Non Meuble', max_length=50)),
                ('description', models.TextField(default='write your description')),
                ('floor', models.IntegerField(default=1)),
                ('bank_receipt', models.FileField(upload_to='bank_receipts')),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appartement.Appartement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
