# Generated by Django 3.0.5 on 2020-10-10 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0005_auto_20201010_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='init_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
    ]
