# Generated by Django 3.0.5 on 2020-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0006_auto_20201010_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingform',
            name='state',
            field=models.CharField(default='non confirme', max_length=15),
        ),
        migrations.AlterField(
            model_name='buyingform',
            name='bank_receipt',
            field=models.FileField(blank=True, upload_to='bank_receipts'),
        ),
    ]
