# Generated by Django 3.0.5 on 2020-10-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0008_auto_20201010_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingform',
            name='description',
            field=models.TextField(blank=True, default='write your description', null=True),
        ),
        migrations.AlterField(
            model_name='buyingform',
            name='state',
            field=models.CharField(blank=True, default='non confirme', max_length=15),
        ),
    ]
