# Generated by Django 3.1.2 on 2020-10-15 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0009_auto_20201012_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingform',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buyingform',
            name='phoneNumber',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
