# Generated by Django 3.1.2 on 2020-10-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0010_auto_20201015_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phoneNumber',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
