# Generated by Django 3.1.2 on 2020-10-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appartement', '0011_auto_20201015_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phoneNumber',
        ),
    ]
